# Generated by Django 4.2 on 2023-07-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.CharField(max_length=1000)),
                ('value_b', models.CharField(max_length=1000)),
                ('projectlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flashcardset')),
            ],
        ),
    ]
