# Generated by Django 4.2 on 2023-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='identifier',
            field=models.CharField(default='dsh54jfk', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
