# Generated by Django 4.2 on 2023-07-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flashcardset_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcardset',
            old_name='description',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='flashcardset',
            old_name='creator',
            new_name='ersteller',
        ),
    ]
