# Generated by Django 4.2 on 2023-07-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_ersteller_flashcardset_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='projectlist',
            new_name='flashcardset',
        ),
    ]
