# Generated by Django 4.2 on 2023-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_projectlist_flashcard_flashcardset'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='identifier',
            field=models.CharField(default='abcd', max_length=40),
            preserve_default=False,
        ),
    ]
