# Generated by Django 4.2 on 2023-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_flashcard_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='identifier',
            field=models.CharField(max_length=40),
        ),
    ]
