# Generated by Django 4.2 on 2023-07-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_flashcard_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='password',
            field=models.CharField(default='amogus', max_length=60),
            preserve_default=False,
        ),
    ]
