# Generated by Django 4.2 on 2024-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_flashcard_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='short_id',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
