# Generated by Django 4.2 on 2024-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_flashcardset_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='short_id',
            field=models.IntegerField(unique=True),
        ),
    ]
